Adding GHA CRANapt/bspm support for the installation of R binary packages

diff --git a/.github/workflows/fcb_autograding.yml b/.github/workflows/fcb_autograding.yml
--- a/.github/workflows/fcb_autograding.yml
+++ b/.github/workflows/fcb_autograding.yml
@@ -20,20 +20,22 @@ jobs:
           r-version: ${{ matrix.r-version }}
       - name: Set up pandoc
         uses: r-lib/actions/setup-pandoc@v2
+      - name: Set up CRANapt for R binary packages
+        run: sudo Rscript --vanilla -e 'install.packages("bspm", repos="https://cran.r-project.org")' ; sudo wget -q -O- https://eddelbuettel.github.io/r2u/assets/dirk_eddelbuettel_key.asc | sudo tee -a /etc/apt/trusted.gpg.d/cranapt_key.asc ; echo "deb [arch=amd64] https://dirk.eddelbuettel.com/cranapt focal main" | sudo tee /etc/apt/sources.list.d/cranapt.list ; sudo apt update ; sudo wget -q -O- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc ; echo "deb [arch=amd64] https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/" | sudo tee /etc/apt/sources.list.d/cran-ubuntu.list
       - name: Install development packages
-        run: Rscript -e 'install.packages(c("remotes", "rprojroot", "renv", "desc", "rmarkdown", "knitr"))' ; Rscript -e 'remotes::install_github("jalvesaq/colorout")'
+        run: Rscript --vanilla -e 'options(bspm.sudo=TRUE) ; suppressMessages(bspm::enable()) ; install.packages(c("remotes", "rprojroot", "renv", "desc", "rmarkdown", "knitr"), repos="https://cran.r-project.org")'
       - name: Install package dependencies
-        run: Rscript -e 'library(colorout) ; pkg_deps <- renv::dependencies()$Package ; missing_pkgs <- setdiff(pkg_deps, rownames(installed.packages())) ; if (length(missing_pkgs) > 0) { res <- tryCatch({ install.packages(missing_pkgs) ; TRUE }, error=function(cond) { message(cond) ; return(FALSE) }, warning=function(cond) { message(cond) ; return(FALSE) }) ; if (!res) { stop("PROBLEMS INSTALLING PACKAGE DEPENDENCIES. SEE MESSAGES ABOVE.") } }'
+        run: Rscript --vanilla -e 'options(bspm.sudo=TRUE) ; suppressMessages(bspm::enable()) ; pkg_deps <- renv::dependencies()$Package ; missing_pkgs <- setdiff(pkg_deps, rownames(installed.packages())) ; if (length(missing_pkgs) > 0) { res <- tryCatch({ install.packages(missing_pkgs, repos="https://cran.r-project.org") ; TRUE }, error=function(cond) { message(cond) ; return(FALSE) }, warning=function(cond) { message(cond) ; return(FALSE) }) ; if (!res) { stop("PROBLEMS INSTALLING PACKAGE DEPENDENCIES. SEE MESSAGES ABOVE.") } }'
       - name: Check for index.Rmd
         run: RED='\033[0;31m'; NC='\033[0m' ; if [ -e index.Rmd ] ; then exit 0 ; else { echo -e "${RED}MISSING FILE index.Rmd${NC}" ; exit 1 ; } ; fi
       - name: Check for index.html
-        run: RED='\033[0;31m'; NC='\033[0m' ; if [ -e index.Rmd ] || [ -e docs/index.html ] ; then exit 0 ; else { echo -e "${RED}MISSING FILE index.html${NC}" ; exit 1 ; } ; fi
+        run: RED='\033[0;31m'; NC='\033[0m' ; if [ -e index.html ] || [ -e docs/index.html ] ; then exit 0 ; else { echo -e "${RED}MISSING FILE index.html${NC}" ; exit 1 ; } ; fi
       - name: Check for setwd() in Rmd files
         run: RED='\033[0;31m'; NC='\033[0m' ; nlswd=`grep -n setwd *.Rmd | cut -d ':' -f 1` ; if [ "$nlswd" != "" ] ; then { echo -e "${RED}YOU ARE CALLING setwd() in an .Rmd FILE, PLEASE DO NOT DO IT${NC}" ; exit 1 ; } ; else { exit 0 ; } ; fi
       - name: Check for the absence of R code
-        run: Rscript -e 'library(colorout) ; library(knitr) ; fl <- list.files(pattern=".Rmd$") ; n <- 0 ; for (f in fl) { f2 <- purl(f, documentation=0L) ; r <- readLines(f2) ; n <- n + length(r) } ; if (n < 10) { stop("TOO FEW LINES OF R CODE IN RMARKDOWN FILES") }'
+        run: Rscript -e 'library(knitr) ; fl <- list.files(pattern=".Rmd$") ; n <- 0 ; for (f in fl) { f2 <- purl(f, documentation=0L) ; r <- readLines(f2) ; n <- n + length(r) } ; if (n < 10) { stop("TOO FEW LINES OF R CODE IN RMARKDOWN FILES") }'
       - name: Check for non-ascii characters in object names
-        run: Rscript -e 'library(colorout) ; library(knitr) ; fl <- list.files(pattern=".Rmd$") ; n <- 0 ; for (f in fl) { f2 <- purl(f, documentation=0L) ; r <- getParseData(parse(f2, keep.source=TRUE)) ; obj <- unique(r$text[which(r$token == "SYMBOL")]) ; mask <- grepl("[^ -~]", obj) ; if (any(mask)) { stop(sprintf("PLEASE DO NOT USE NON-ASCII OBJECT NAMES SUCH AS %s IN FILE %s", paste(obj[mask][1:min(c(3, sum(mask)))], collapse=", "), f)) } }'
+        run: Rscript -e 'library(knitr) ; fl <- list.files(pattern=".Rmd$") ; n <- 0 ; for (f in fl) { f2 <- purl(f, documentation=0L) ; r <- getParseData(parse(f2, keep.source=TRUE)) ; obj <- unique(r$text[which(r$token == "SYMBOL")]) ; mask <- grepl("[^ -~]", obj) ; if (any(mask)) { stop(sprintf("PLEASE DO NOT USE NON-ASCII OBJECT NAMES SUCH AS %s IN FILE %s", paste(obj[mask][1:min(c(3, sum(mask)))], collapse=", "), f)) } }'
       - name: Render index.html
         run: if [ -e Makefile ] ; then { echo Makefile found, touching prerequisites ; grep '^[^#[:space:]].*:' Makefile | sed 's/^[^#[:space:]].*:[[:space:]]*//' | sed 's/ /\'$'\n/g' | egrep '\.R|\.Rmd|\.py|\.sh' | xargs touch ; echo Running Makefile ; make ; } ; else { if [ -e _site.yml ] ; then { Rscript -e 'rmarkdown::render_site()' ; } ; else { Rscript -e 'rmarkdown::render("index.Rmd")' ; } ; fi ; } ; fi
       - name: Check for Makefile, .R or .Rmd files in the docs directory
